### ISSUE TITLE
Nuclei Segmentation Model

### ISSUE THREAD

**Issue by nikku1234** [tommy-qichang/AsynDGAN#13]
For the results produced in the paper for nuclei segmentation, which model was used?

**Comment by tommy-qichang** [comment]
Hi @nikku1234 , sorry for my late response.

You can use asyndgan_model https://github.com/tommy-qichang/AsynDGAN/blob/master/models/asyndgan_model.py#L112 for training and pix2pix_model for testing since you just neet the generator. 

Also, please notice to change the discriminator number in the model file. for instance:
https://github.com/tommy-qichang/AsynDGAN/blob/767b20d99f4d1cabf6e12a2c213ffa05a64bb74e/models/asyndgan_model.py#L112

**Comment by nikku1234** [comment]
Okay, thanks! My doubt was did you guys use MASK-RCNN for the segmentation process, for nuclei?

**Comment by huiqu18** [comment]
@nikku1234 The synthetic dataset was generated using the code @tommy-qichang mentioned. After that, we used U-net instead of Mask-RCNN for nuclei segmentation on the synthetic dataset. Training details can be found in Section 4.2 of the paper.

**Comment by nikku1234** [comment]
Okay, thanks @huiqu18  and @tommy-qichang !
