### ISSUE TITLE
Can you provide pre-trained generator on BraTs 2018 dataset?

### ISSUE THREAD

**Issue by XuzheZ** [tommy-qichang/AsynDGAN#7]
Hi Tommy,

Thank you for your inspiring work! It looks interesting to me. I was wondering if it was possible that you can provide your pre-trained label-to-image generator based on BraTs 2018 dataset? It would be very much appreciated if possible! Thank you again.

**Comment by tommy-qichang** [comment]
Hi XuzheZ,

Sorry for my late response.
You could download the latest model from here:
[https://drive.google.com/file/d/1CEAbvknYehaPG-B42jAvKBvwH-HOag5a/view?usp=sharing](https://drive.google.com/file/d/1CEAbvknYehaPG-B42jAvKBvwH-HOag5a/view?usp=sharing)

Please note, when generating synthetic images, you should direct use `pix2pix` model since you only need generator without any distributed discriminators.

**Comment by XuzheZ** [comment]
> Hi XuzheZ,
> 
> Sorry for my late response.
> You could download the latest model from here:
> https://drive.google.com/file/d/1CEAbvknYehaPG-B42jAvKBvwH-HOag5a/view?usp=sharing
> 
> Please note, when generating synthetic images, you should direct use `pix2pix` model since you only need generator without any distributed discriminators.

Thank you very much for sharing the model!
